### ISSUE TITLE
Image not coming back to original position (Chrome)

### ISSUE THREAD

**Issue by isoriaizquierdo** [yyx990803/zoomerang#20]
It seems that theres a new problem with zoomerang in Chrome.

When I zoom an image and then close it, the image doesn't come back to the original position, it applies a transform: translate(_px, _px);

It has to be some update from Chrome because previously was working fine.
You can see what I mean in your demo (mickey image): http://yyx990803.github.io/zoomerang/
In Safari works all fine.

Chrome's version I'm using:
44.0.2403.130 (64-bit)

Any idea of what it could be?
Thanks!

**Comment by lzx1022** [comment]
I meet this problem too. 
And it's about the newest Chrome too.

**Comment by akralj** [comment]
Same problem here: 
does not work under chrome 44, windows
works in chrome 43 windows, firefox 38, windows, chromium 43 ubuntu
probably a chromium bug then?

**Comment by dkribeiro** [comment]
same problem here

**Comment by divmgl** [comment]
+1, still having this issue with Chrome

**Comment by pketh** [comment]
+1

**Comment by hootlex** [comment]
+1

**Comment by specious** [comment]
Here is a screenshot showing the problem on Chrome **49.0.2587.3 dev (64-bit)** on OS X 10.11:

![zoomerang-element-returned-to-incorrect-position](https://cloud.githubusercontent.com/assets/451178/11916387/ef437c98-a6a2-11e5-8bf7-8bb402f93ccd.png)

The object inspector shows the image element having attribute `style="transform: translate(-411.203px, 83.3125px);"` after returning.

Chrome **43.0.2349.4 canary (64-bit)** exhibits desired behavior.

**Comment by devcem** [comment]
+1

**Comment by ganpeng** [comment]
图片回不到原来的位置，大牛

**Comment by Mati365** [comment]
+1 firefox

**Comment by divmgl** [comment]
I've opened a pull request for this issue; please confirm that it's now working

**Comment by yyx990803** [comment]
Fixed in 0.1.10.
